languageCode = "en-us"
title = "World Hacks"
BaseUrl= "http://jice.lavocat.name/blog/"
LanguageCode= "fr-FR"
Title= "World Hacks"
paginate = 15
DisqusShortname = "jicelavocat"
Copyright = "All rights reserved - 2016"
theme = "casper_jice"
canonifyurls = true

[permalinks]
  post= "/:year/:title/"

[params]
  Description = "French/English essays about our Digital World, about Nature and Mind"
  cover = "images/coverCalvi.png"
  author = "Jean-Christophe Lavocat"
  authorlocation = "Toulon, France"
  authorwebsite = "http://jice.lavocat.name"
  bio = "World citizen, often found in France. Currently trying to build a Startup named <a href='http://www.elokenz.com'>Elokenz</a> : a SaaS about Content Marketing and Social Media."
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-3492655-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = "http://feeds.feedburner.com/jice_lavocat"
  githubName = "tanzaho"
  googlePlusName = "+jice_lavocat"
  twitterName = "jice_lavocat"
  facebookName = "jean.christophe.gomez.lavocat"
  linkedinName = "9743130"
  newsletterLink = "http://eepurl.com/Argdf"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false


[[menu.main]]
  name = "My Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About me"
  weight = -110
  identifier = "about"
  url = "/about"
